# Generated by Django 3.0.8 on 2020-08-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_course_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileimage', models.ImageField(upload_to='portfolio/images/')),
                ('file_name', models.CharField(max_length=300)),
                ('publicher', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
