# Generated by Django 3.0.8 on 2020-08-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_libfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibFile',
        ),
    ]
