# Generated by Django 3.0.8 on 2020-08-06 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_delete_libfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileimage', models.ImageField(upload_to='portfolio/images/')),
                ('partition_name', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LibFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileimage', models.ImageField(upload_to='portfolio/images/')),
                ('file_name', models.CharField(max_length=300)),
                ('publicher', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('upload', models.FileField(upload_to='uploads/')),
                ('like', models.IntegerField(default=0)),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.LibPartition')),
            ],
        ),
    ]
