# Generated by Django 3.0.8 on 2020-08-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_libfile_libpartition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='like',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='text4',
        ),
        migrations.CreateModel(
            name='lesson_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('textimg', models.ImageField(blank=True, upload_to='')),
                ('text1', models.TextField()),
                ('text2', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('text4', models.TextField(blank=True)),
                ('like', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.lesson')),
            ],
        ),
    ]
