# Generated by Django 3.0.8 on 2020-08-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200809_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_detail',
            old_name='course',
            new_name='lesson',
        ),
    ]
