# Generated by Django 3.0.8 on 2020-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_messageservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_imag',
            field=models.ImageField(null=True, upload_to='portfolio/images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_text',
            field=models.TextField(null=True),
        ),
    ]
