# Generated by Django 3.0.8 on 2020-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_messageblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageblog',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
