# Generated by Django 3.0.8 on 2020-08-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_messagedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
