# Generated by Django 3.0.8 on 2020-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
